steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-f'
  - 'uat.dockerfile'
  - '--build-arg' 
  - 'JDBC_PASSWORD'
  - '-t'
  - 'gcr.io/mockazon/uatimage:maven-env'
  - '.'
  secretEnv: ['JDBC_PASSWORD']
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/mockazon/uatimage:maven-env'
- name: "gcr.io/cloud-builders/gcloud"
  args:
  - 'app'
  - 'deploy'
  - 'uat/app.yaml'
  - '--image-url'
  - 'gcr.io/mockazon/uatimage:maven-env'
images:
  - 'gcr.io/mockazon/uatimage:maven-env'
secrets:
- kmsKeyName: projects/mockazon/locations/us-central1/keyRings/mockazon_ring/cryptoKeys/sql_pass
  secretEnv:
    JDBC_PASSWORD: CiQAhVODvDHx5P9ub7srcZDJMMFiyQAMrKDYBKtZpZHx9268iqISMQAGs0POtHa5fKdg983lPU6lAUrvwXo1u0J7ggTPdU7FxQLHYOnQCEsg2XaZ61iqD/k=
# timeout: "600s"

