language: java
sudo: true
dist: trusty
#trusty may be the incorrect distro. Check this if there are problems
jdk: oraclejdk9
cache:
  directories:
   - $HOME/google-cloud-sdk
services:
 - docker
env:
  global:
   - CLOUDSDK_CORE_DISABLE_PROMPTS=1
   - ENV DATABASE_NAME="mockazon"
   - ENV JDBC_SCHEMA="mockazon"
   - ENV JDBC_URL="35.192.64.159"
   - ENV JDBC_USERNAME="postgresql"
   - ENV JDBC_PASSWORD="password"
addons:
 apt:
   packages:
     - oracle-java9-installer
before_install:
 - chmod +x mvnw
# - ./install.sh
 - if [ ! -d $HOME/google-cloud-sdk/bin ]; then
  rm -rf $HOME/google-cloud-sdk;
  curl https://sdk.cloud.google.com | bash > /dev/null;
  fi
 - source $HOME/google-cloud-sdk/path.bash.inc
 - gcloud components update kubectl
 - gcloud version
install: true
script: 
# - ./install.sh
# - ./deploy.sh