language: java
sudo: true
dist: trusty
#trusty may be the incorrect distro. Check this if there are problems
jdk: oraclejdk9
cache:
  directories:
   - $HOME/google-cloud-sdk
services:
 - docker
addons:
 apt:
   packages:
     - oracle-java9-installer
before_install:
 - chmod +x mvnw
 - chmod +x ./install.sh
 - chmod +x ./deploy.sh
 - chmod +x ./configure.sh
# - ./install.sh
# - if [ ! -d $HOME/google-cloud-sdk/bin ]; then
#  rm -rf $HOME/google-cloud-sdk;
#  curl https://sdk.cloud.google.com | bash > /dev/null;
#  fi
# - source $HOME/google-cloud-sdk/path.bash.inc
# - gcloud components update kubectl -y
# - gcloud version
# install: true
script: 
 - ./install.sh
 - gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
 - ./configure.sh
after_success:
 - ./deploy.sh