language: java
sudo: true
dist: trusty
jdk: oraclejdk8
cache:
  directories:
   - $HOME/google-cloud-sdk
services:
 - docker
addons:
 apt:
   packages:
     - oracle-java8-installer
before_install:
 - chmod +x mvnw
 - openssl aes-256-cbc -K $encrypted_b853e1ba22a9_key -iv $encrypted_b853e1ba22a9_iv -in gcpdemosbmongeon-e25e1414c004.json.enc -out gcpdemosbmongeon-e25e1414c004.json -d
script: 
 - gcloud auth activate-service-account --key-file=gcpdemosbmongeon-e25e1414c004.json