language: java
sudo: true
dist: trusty
#trusty may be the incorrect distro. Check this if there are problems
jdk: oraclejdk9
cache:
  directories:
   - $HOME/google-cloud-sdk
services:
 - docker
addons:
 apt:
   packages:
     - oracle-java9-installer
before_install:
 - chmod +x mvnw
 - chmod +x ./configure.sh
 - chmod +x ./deploy.sh
 - openssl aes-256-cbc -K $encrypted_b853e1ba22a9_key -iv $encrypted_b853e1ba22a9_iv -in gcpdemosbmongeon-e25e1414c004.json.enc -out gcpdemosbmongeon-e25e1414c004.json -d
after_success:
 - ./deploy.sh