apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mockazon
spec:
  revisionHistoryLimit: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: mockazon
    spec:
      containers:
      - name: mockazon
        image: gcr.io/gcpdemosbmongeon/mockazon:v1.0
        env:
        - name: JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jdbc-password
              key: key
        - name: DATABASE_NAME
          value: "postgres"
        - name: JDBC_SCHEMA
          value: "mockazon"
        - name: JDBC_URL
          value: "35.192.64.159"
        - name: JDBC_USERNAME
          value: "postgres"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        resources:
          limits:
            cpu: 70m
          requests:
            cpu: 70m

---
apiVersion: v1
kind: Service
metadata:
  name: mockazon
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: mockazon