apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mockazon
spec:
  revisionHistoryLimit: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: mockazon
    spec:
      containers:
      - name: mockazon
        image: gcr.io/gcpdemosbmongeon/mockazon:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        resources:
          limits:
            cpu: 70m
          requests:
            cpu: 70m
---
apiVersion: v1
kind: Service
metadata:
  name: mockazon
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: mockazon